name: test

on:
  push:
    branches:
      - main
      - staging

  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
      - name: Give GitHub Actions access
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SECRET_REPO_DEPLOY_KEY }}
      - run: cargo test
